version: '3.8'
services:
  app:
    container_name: mongoose_embedding_app
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
    depends_on:
      - mongo
  # MongoDB
  mongo:
    container_name: mongoose_embedding_mongo
    image: 'mongo:5.0.3'
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db
volumes:
  db: